# Generated by Django 4.1.4 on 2022-12-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinno', models.CharField(max_length=12)),
                ('mats', models.CharField(max_length=12)),
                ('phys', models.CharField(max_length=12)),
                ('chem', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='pinno',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\komal\\Desktop\\Python\\kai\\Project\\Media/', verbose_name=''),
        ),
    ]
